Repository WildCodeSchool/2023-09-js-tlse-p2-cocktail-atom, pull requests merged in 2023-11, with the labels that each got.

#3 S2 us5/navbar
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/favicon.svg
  frontend/src/assets/fonts/JejuGothic-Regular.ttf
  frontend/src/assets/fonts/OleoScript-Regular.ttf
  frontend/src/assets/icons/burger.svg
  frontend/src/assets/icons/filter.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/logo.svg
  frontend/src/components/Counter.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
Labels: Reviewed

#4 S2 us4/cocktail card
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/icons/fillHeart.svg
  frontend/src/assets/icons/unfillHeart.svg
  frontend/src/components/Card.jsx
  frontend/src/components/Card.scss
Labels: Reviewed, Corrections done

#5 S3 us14/nav burger
  frontend/src/App.css
  frontend/src/assets/icons/quit.svg
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
  frontend/src/components/OverlayBurger.jsx
  frontend/src/components/OverlayBurger.scss
Labels: Reviewed

#8 feat: project restart,add data,add filter card button
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Data.jsx
  frontend/src/components/Data.scss
  frontend/src/components/FilterCardButton.jsx
  frontend/src/components/Navbar.jsx
Labels: Reviewed

#9 S3 us3/search bar
  frontend/.env.sample
  frontend/src/App.jsx
  frontend/src/components/CocktailBySearch.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
  frontend/src/components/OverlayBurger.scss
  frontend/src/contexts/ApiContext.jsx
  frontend/src/main.jsx
Labels: Reviewed

#10 S4 us9/footer
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/icons/instagram.svg
  frontend/src/assets/icons/mail.svg
  frontend/src/assets/icons/twitter.svg
  frontend/src/components/Footer.jsx
  frontend/src/components/Footer.scss
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
Labels: Reviewed

#11 S4 us2/filter
  frontend/src/components/ FilterCardButton.jsx
  frontend/src/components/AlertAge.jsx
  frontend/src/components/CocktailBySearch.jsx
  frontend/src/components/Data.jsx
  frontend/src/components/Data.scss
  frontend/src/components/FilterCardButton.jsx
  frontend/src/components/FilterCardButton.scss
  frontend/src/components/FilterMiniCard.jsx
  frontend/src/components/FilterMiniCard.scss
  frontend/src/components/MiniCard.jsx
  frontend/src/components/MiniCard.scss
  frontend/src/components/Navbar.jsx
Labels: Reviewed

#13 S4 us16/route system
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/AboutUs.jsx
  frontend/src/components/AboutUs.scss
  frontend/src/components/AlertAge.jsx
  frontend/src/components/Data.jsx
  frontend/src/components/FilterCardButton.jsx
  frontend/src/components/FilterMiniCard.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Footer.scss
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
  frontend/src/components/OverlayBurger.jsx
  frontend/src/components/OverlayBurger.scss
  frontend/src/contexts/ApiContext.jsx
  frontend/src/main.jsx
Labels: Changes requested, Reviewed

#14 chore: modify style of filter and remove unused function
  frontend/src/components/CocktailBySearch.jsx
  frontend/src/components/Data.jsx
  frontend/src/components/Data.scss
  frontend/src/components/FilterCardButton.jsx
  frontend/src/components/FilterCardButton.scss
  frontend/src/components/Navbar.jsx
  frontend/src/components/OverlayBurger.jsx
  frontend/src/main.jsx
Labels: Reviewed

#15 chore: adding style to MiniCard
  frontend/src/components/MiniCard.scss
  frontend/src/components/OverlayBurger.jsx
Labels: Reviewed

#18 feat: to modify style mini card
  frontend/src/components/FilterCardButton.scss
  frontend/src/components/MiniCard.scss
Labels: Reviewed

#19 S4 us7/random cocktail
  frontend/src/components/MiniCard.jsx
  frontend/src/components/MiniCard.scss
Labels: Reviewed

#21 fix: modify style detail
  frontend/src/App.css
  frontend/src/components/FilterCardButton.scss
  frontend/src/components/Footer.scss
  frontend/src/components/MiniCard.scss
  frontend/src/components/SecondCarousel.jsx
Labels: Reviewed

#22 Merge dev to main S4
  frontend/.env.sample
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/fonts/JejuGothic-Regular.ttf
  frontend/src/assets/fonts/OleoScript-Regular.ttf
  frontend/src/assets/icons/burger.svg
  frontend/src/assets/icons/fillHeart.svg
  frontend/src/assets/icons/filter.svg
  frontend/src/assets/icons/instagram.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/mail.svg
  frontend/src/assets/icons/quit.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/icons/twitter.svg
  frontend/src/assets/icons/unfillHeart.svg
  frontend/src/assets/images/Cosmopolitain.jpg
  frontend/src/assets/images/Daquiri.jpg
  frontend/src/assets/images/Dry-Martini.jpg
  frontend/src/assets/images/Gimlet.jpg
  frontend/src/assets/images/Manhattan.jpg
  frontend/src/assets/images/Margarita.jpg
  frontend/src/assets/images/Mimosa.jpg
  frontend/src/assets/images/Mojito.jpg
  frontend/src/assets/images/Negroni.jpg
  frontend/src/assets/images/Old-fashioned.jpg
  frontend/src/assets/images/home-cocktail.jpg
  frontend/src/components/AboutUs.jsx
  frontend/src/components/AboutUs.scss
  frontend/src/components/AlertAge.jsx
  frontend/src/components/AlertAge.scss
  frontend/src/components/Card.jsx
  frontend/src/components/Card.scss
  frontend/src/components/Carousel.jsx
  frontend/src/components/Carousel.scss
  frontend/src/components/CocktailBySearch.jsx
  frontend/src/components/Data.jsx
  frontend/src/components/Data.scss
  frontend/src/components/FilterCardButton.jsx
  frontend/src/components/FilterCardButton.scss
  frontend/src/components/FilterMiniCard.jsx
  frontend/src/components/FilterMiniCard.scss
  frontend/src/components/Footer.jsx
  frontend/src/components/Footer.scss
  frontend/src/components/HomePage.jsx
  frontend/src/components/HomePage.scss
  frontend/src/components/MiniCard.jsx
  frontend/src/components/MiniCard.scss
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
  frontend/src/components/OverlayBurger.jsx
  frontend/src/components/OverlayBurger.scss
  frontend/src/components/RandomCocktail.jsx
  frontend/src/components/RandomCocktail.scss
  frontend/src/components/SecondCarousel.jsx
  frontend/src/components/SecondCarousel.scss
  frontend/src/contexts/ApiContext.jsx
  frontend/src/main.jsx
Labels: Reviewed

#23 S4 us18/detail
  frontend/index.html
Labels: Reviewed
